### ISSUE TITLE
SSL mode hard-coded to false, prevents connection

### ISSUE THREAD

**Issue by dominics** [Gusto/aptible_datadog_postgres_monitor#6]
I'm not sure if this is peculiar to the particular Postgres instances I'm looking at, but on my Aptible account, I cannot connect to the databases unless the ssl flag is set to true. The error I receive is:

```
InterfaceError: md5 password authentication failed
```

When I log into the built container (using something like `aptible ssh`) I can see configs are being properly written out to `/etc/dd-agent/conf.d/postgres.yaml` like:

```
- dbname: postgres
  host: db-blah-1234.aptible.in
  password: foo
  port: 12345
  ssl: false
  tags:
  - aptible_env:foo
  username: datadog
```

And when I test these configs, using `python /opt/datadog-agent/agent/agent.py check postgres --profile` in that container, I receive connection errors until I set the SSL flag to true (at which point everything works nicely again). It's currently hard-coded to false at https://github.com/Gusto/aptible_datadog_postgres_monitor/blob/0fdf3e040a0b73d5937d5694e70d6bf2cb38aa03/entrypoint.py#L18

Perhaps Aptible have turned on SSL support for their database instances recently?
